### PR TITLE
Fix binary data in the response and add Promise type bindings for Assets

### LINKED ISSUE #168: Binary data returned as string instead of Buffer
I found out `getAssetReportPdf` does not return `Buffer`, but `string` because the Request `encoding` option defaults to `utf8`, while binary data need `null` - see the docs:

> encoding - encoding to be used on setEncoding of response data. If null, the body is returned as a Buffer. Anything else (including the default value of undefined) will be passed as the encoding parameter to toString() (meaning this is effectively utf8 by default). (Note: if you expect binary data, you should set encoding: null.

`plaidRequest` should have a boolean flag to to mark Plaid operation as the one returning binary data.

### LINKED ISSUE #170: createAssetReport options are not sent with the request when wrapped in Promise
When I call 

```javascript
createAssetReport(access_tokens: Array<string>,
                  days_requested: number,
                  options: AssetReportCreateOptions): Promise
```

The options are not sent with the request. The reason is the implementation adds `options` directly to the `body` instead of passing it further as an argument to `_authenticatedRequest`:

https://github.com/plaid/plaid-node/blob/1cccac36bd97cc551941df01b3cb6289f285a3d3/lib/PlaidClient.js#L257-L267

I.e. for clarification `_authenticatedRequest` is called as `_authenticatedRequest(requestSpec, options)` where `options` value is `cb` (argument shift). Since `cb` is `undefined` (using the `Promise` variant), the condition inside `_authenticatedRequest` goes to `else` part and effectively overwrites the `options` with `undefined`.

https://github.com/plaid/plaid-node/blob/1cccac36bd97cc551941df01b3cb6289f285a3d3/lib/PlaidClient.js#L47-L55

### PR DESCRIPTION
**Pull request by byF**
1. `index.d.ts` did not have `Promise` based signatures for Assets-related methods
2. ~~`getAssetReportPdf` was returning only `Buffer` and hence losing request id which is provided in `Plaid-Request-Id` HTTP header~~
2. `getAssetReportPdf` returned incorrect data (closes #168) and also losing request id in the process which was provided in `Plaid-Request-Id` HTTP header
3. I use Intellij so I modified `.gitignore` accordingly
4. The options were not sent in `createAssetReport` (closes #170 )

### CODE REVIEW

**Comment by byF** [comment]
So I found out `getAssetReportPdf` does not return `Buffer`, but `string`; I assume it's because of encoding - see `request` docs:

> encoding - encoding to be used on setEncoding of response data. If null, the body is returned as a Buffer. Anything else (including the default value of undefined) will be passed as the encoding parameter to toString() (meaning this is effectively utf8 by default). (Note: if you expect binary data, you should set encoding: null.

That explains when I save the output from `getAssetReportPdf` I get an empty PDF with several pages and 1.5x size in comparison with a PDF fetched with curl directly.

**Comment by byF** [comment]
Hi @ntindall I can't request the review through PR so I'll bother you manually :)

**Comment by ntindall** [comment]
thanks @byF  -- we'll take a look

File: lib/plaidRequest.js [hunk 1]
```diff
@@ -28,6 +28,13 @@ var handleApiResponse = function(resolve, reject, err, res, $body, isMfa) {
 
   // success response (non mfa)
   } else if (res.statusCode === 200) {
+    // when Plaid-Request-Id exists we assume binary data are returned
+    if (res.headers['plaid-request-id']) {
```
Comment (ntindall) [inline lib/plaidRequest.js]: @dsfish @r-ohan is this a safe assumption to make? I feel like this may be the case only by coincidence.

A possible alternative might be to implement some sort of `PlaidBuffer` class that extends Buffer and has some method like `.RequestId()` available?

File: lib/PlaidClient.js [hunk 2]
```diff
@@ -285,6 +285,7 @@ function(asset_report_token, cb) {
     body: {
       asset_report_token: asset_report_token,
     },
+    binary: true,
```
Comment (ntindall) [inline lib/PlaidClient.js]: I am guessing that the current behavior is that we return a base64 encoded string, is that right @byF ? You could convert this back into a buffer if you needed to, no? 

I'm a bit wary of this change, since it is a breaking change in the clien'ts API - assuming the current implementation does work in the way I posited above. Perhaps I am missing something, though.

File: index.d.ts [hunk 3]
```diff
@@ -375,6 +375,10 @@ declare module 'plaid' {
     warnings: Array<Warning>;
   }
 
+  interface AssetReportGetPdfResponse extends BaseResponse {
```
Comment (ntindall) [inline index.d.ts]: thanks for adding these typings 👍 we should definitely add them regardless of what we land on w.r.t. the buffer.

File: lib/PlaidClient.js (hunk 2 above)
Comment (byF) [reply lib/PlaidClient.js]: Nope, it's not that case unfortunately (or I missed something). The request lib was encoding the binary data as utf8 string which made them unusable.

I didn't figure out how to work around it (tried various Buffer.from variations, but nothing produced correct binary data), that's why I digged through the library to fix it :)

Comment (byF) [reply lib/PlaidClient.js]: Also regarding breaking change - bindings say it returns `Buffer`, so anyone who depends on it knows they work around a bug (I don't know how though, I'd love to learn that)

File: lib/plaidRequest.js (hunk 1 above)
Comment (r-ohan) [reply lib/plaidRequest.js]: @dsfish do we return a `Content-Type` header? That seems to be the ideal way of handling this. It doesn't look like we do from what I can tell. It would be a pretty easy fix to implement.

Comment (byF) [reply lib/plaidRequest.js]: @r-ohan you do return it :)

Comment (r-ohan) [reply lib/plaidRequest.js]: Yeah eventually moving request_id's into the headers for all responses seems like something we'd want to to do, but I doubt that it's something we can tackle anytime soon. (cc @nathankot )

We shouldn't assume that if a request_id is sent in the header that the response type is binary, this doesn't seem like a future-proof solution. Can you add a check for `Content-Type` to line 32 as well? If we do decide to move request_id to headers it'll most likely come with a change to the client libs to handle the change.

**Comment by dsfish** [comment]
@ntindall + @r-ohan, it looks like you've got this covered. LMK if you need me to review this.

Thanks for making these changes, @byF!

File: lib/plaidRequest.js (hunk 1 above)
Comment (byF) [reply lib/plaidRequest.js]: @r-ohan Sure, just to make sure we understand each other:
```javascript
if (res.headers['plaid-request-id'] && res.headers['content-type']==='application/pdf') {
```
correct?

Comment (r-ohan) [reply lib/plaidRequest.js]: That looks good - I think we can go a step further and say that any content type starting with `application` will be a binary data type. [Explanation of the application mime type for reference.](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#Discrete_types)

So it should look like this:

```node
if (res.headers['plaid-request-id'] && res.headers['content-type'] && res.headers['content-type'].indexOf('application') === 0) {
```

Thanks for your help with this!!

Comment (byF) [reply lib/plaidRequest.js]: Cool, good catch with the `application` mime-type 👍

**Comment by byF** [comment]
@ntindall @r-ohan anything left for the review?

**Comment by byF** [comment]
Okay, so I found another bug - the options are not propagated correctly in `createcreateAssetReport`. The fix is simple, I'll post an issue and push the commit in a few minutes.

**Comment by byF** [comment]
So... a conundrum. The test fails because it correctly propagates the webhook now; the webhook points to `www.example.com`:

https://github.com/plaid/plaid-node/blob/1cccac36bd97cc551941df01b3cb6289f285a3d3/test/PlaidClientTest.js#L747-L752

I'd say it points to a bug inside API implementation. For whatever reason it's not possible to poll an asset report when a webhook is provided.

On the other side, it might be a feature - when webhook is provided, it's not possible to poll the asset report. However, the documentation does not state anything like that.

What's the verdict? :)

File: lib/plaidRequest.js [hunk 4]
```diff
@@ -28,6 +28,16 @@ var handleApiResponse = function(resolve, reject, err, res, $body, isMfa) {
 
   // success response (non mfa)
   } else if (res.statusCode === 200) {
+    // extract request id from header for binary data,
+    // i.e. mime type application/*
+    if (res.headers['plaid-request-id'] &&
```
Comment (ntindall) [inline lib/plaidRequest.js]: we should not rely on the truthiness construct in javascript here - can we explicitly check `!= null` ?

**Comment by r-ohan** [comment]
@dsfish could you take a look at the webhook question? You have much more context than I do.

**Comment by dsfish** [comment]
I looked into this, @byF + @r-ohan. It looks like the test is failing because report generation is taking longer than the allotted 20 seconds. I will investigate this regression, but for now @byF you can unblock yourself by changing `20` to `60` on [this line](https://github.com/plaid/plaid-node/blob/1cccac36bd97cc551941df01b3cb6289f285a3d3/test/PlaidClientTest.js#L849). Sorry about this, and thanks for making these changes! cc @ntindall

File: lib/plaidRequest.js (hunk 4 above)
Comment (byF) [reply lib/plaidRequest.js]: You mean check for `undefined`, right?

Comment (ntindall) [reply lib/plaidRequest.js]: Whether it is `null` or `undefined`, line 35 is going to throw an exception. We can cover both cases with `!= null`.

I think I "happen to know" that its going to be undefined, but there is no harm in being cautious and defensive here.

Comment (r-ohan) [reply lib/plaidRequest.js]: @byF `!= null` checks for both `null` and `undefined`. It should be fine if we just make this line:
```javascript
if (res.headers['plaid-request-id'] != null &&
```
@byF thanks again for all your help here.

Comment (byF) [reply lib/plaidRequest.js]: Thanks for the explanation guys! Commit away.

**Comment by ntindall** [comment]
thanks @byF !

**Comment by r-ohan** [comment]
@byF thanks for your help with this, we'd love to send you some Plaid swag as a token of our appreciation. Do you mind sending over your contact info / mailing address to rohan@plaid.com?
